version: '2'

services:
  lemmy:
    image: {{ lemmy_docker_image }}
    ports:
      - "127.0.0.1:{{ lemmy_port }}:8536"
    restart: always
    environment:
      - RUST_LOG="warn,lemmy_server=info,lemmy_api=info,lemmy_api_common=info,lemmy_api_crud=info,lemmy_apub=info,lemmy_db_queries=info,lemmy_db_schema=info,lemmy_db_views=info,lemmy_db_views_actor=info,lemmy_db_views_moderator=info,lemmy_routes=info,lemmy_utils=info,lemmy_websocket=info"
    volumes:
      - ./lemmy.hjson:/config/config.hjson
    depends_on:
      - postgres
      - pictrs

  lemmy-ui:
    image: {{ lemmy_docker_ui_image }}
    ports:
      - "127.0.0.1:{{ lemmy_ui_port }}:1234"
    restart: always
    environment:
      - LEMMY_UI_LEMMY_INTERNAL_HOST=lemmy:8536
      - LEMMY_UI_LEMMY_EXTERNAL_HOST={{ domain }}
      - LEMMY_UI_HTTPS=true
    volumes:
      - ./volumes/lemmy-ui/extra_themes:/app/extra_themes
    depends_on: 
      - lemmy

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=lemmy
      - POSTGRES_PASSWORD={{ postgres_password }}
      - POSTGRES_DB=lemmy
    command: [
      "postgres",
      # Tune your settings via
      # https://pgtune.leopard.in.ua/#/
      # You can use this technique to add them here
      # https://stackoverflow.com/a/30850095/1655478
      "-c", "max_connections=200",
      "-c", "shared_buffers=3GB",
      "-c", "effective_cache_size=9GB",
      "-c", "maintenance_work_mem=768MB",
      "-c", "checkpoint_completion_target=0.9",
      "-c", "checkpoint_timeout=86400",
      "-c", "wal_buffers=16MB",
      "-c", "default_statistics_target=100",
      "-c", "random_page_cost=4",
      "-c", "effective_io_concurrency=2",
      "-c", "work_mem=4GB",
      "-c", "min_wal_size=1GB",
      "-c", "max_wal_size=30GB",
      "-c", "max_worker_processes=4",
      "-c", "max_parallel_workers_per_gather=2",
      "-c", "max_parallel_workers=4",
      "-c", "max_parallel_maintenance_workers=2"
    ]
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    restart: always

  pictrs:
    image: asonix/pictrs:0.3.1
    user: 991:991
    ports:
      - "127.0.0.1:{{ pictrs_port }}:8080"
    volumes:
      - ./volumes/pictrs:/mnt
    restart: always
    mem_limit: 200m

  postfix:
    image: mwader/postfix-relay
    environment:
      - POSTFIX_myhostname={{ domain }}
    restart: "always"
